plugins {
    id 'java'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '4.0.15'
}

repositories {
    mavenCentral()
}

// Declaramos la versión centralizada para evitar conflictos
def serenityVersion = '4.0.15'

dependencies {
    testImplementation "net.serenity-bdd:serenity-core:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-cucumber:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-rest-assured:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:${serenityVersion}"
    testImplementation "net.serenity-bdd:serenity-screenplay-rest:${serenityVersion}"

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.assertj:assertj-core:3.24.2'
    testImplementation 'org.slf4j:slf4j-simple:2.0.7'
}

test {
    systemProperty "cucumber.filter.tags", System.getProperty("cucumber.filter.tags")
    testLogging.showStandardStreams = true
}

gradle.startParameter.continueOnFailure = true